
POST http://localhost:8085/api/v1/auth/register
Content-Type: application/json

{
    "username": "babacar",
    "password": "123456",
    "phoneNumber": "+221774796838"
}





#########

POST http://localhost:8085/api/v1/auth/verify-otp 
Content-Type: application/json

{
    "code": "323884",
    "userId": "1"
    
}




#########

POST http://localhost:8085/api/v1/auth/login
Content-Type: application/json

{
    "username": "babacar",
    "password": "123456"
}




####