
POST http://localhost:8085/api/v1/mobile/auth/register
Content-Type: application/json

{
    "username": "boubs",
    "password": "123456",
    "phoneNumber": "+221788930107"
}





#########

POST http://localhost:8085/api/v1/mobile/auth/verify-otp 
Content-Type: application/json

{
    "code": "715678",
    "userId": "1"  
}




#########

POST http://localhost:8085/api/v1/mobile/auth/login
Content-Type: application/json

{
    "numeroTelephone": "+221788930107",
    "codeSecret": "1234"
}




####


POST http://localhost:8085/api/v1/mobile/auth/send-otp
Content-Type: application/json

{
    "phoneNumber": "+221788930107",
    "username": "boubs",
    "nom": "boubs",
    "prenom": "boubs",
    "dateNaissance": "2000-01-01",
    "longitude": "10.0",
    "latitude": "10.0"

}

####
POST http://localhost:8085/api/v1/mobile/auth/verify-otp
Content-Type: application/json

{
    "code": "087456",
    "otpId": "1"
    
}

###
POST http://localhost:8085/api/v1/mobile/auth/register
Content-Type: application/json

{
    "otpId": "1",
    "codeSecret": "1234"
}




####

POST http://localhost:8085/api/v1/web/auth/login
Content-Type: application/json

{
    "email": "admin@accel.tech",
    "password": "123456"
    
}


####


GET http://localhost:8085/api/v1/produits


#    private String email;
#     private String password;


// list by ID

###

GET http://localhost:8085/api/v1/produits/1

###

PUT http://localhost:8085/api/v1/web/produits/1
Content-Type: application/json

{
    "libelle": "Nouveau Libellé",
    "description": "Nouvelle Description",
    "prix": 799.99,
    "taille": "Medium",
    "quantity": 15,
    "categorieProduitId": 2,
    "image": null
}


####

GET http://localhost:8085/api/v1/produits/search?nomProduit=Téléphone GoPhone X


###

GET http://localhost:8085/api/v1/produits/search?categorieId=1&prixMin=30


###


GET http://localhost:8085/api/v1/web/produits/paged?page=0&size=2


###

GET http://localhost:8085/api/v1/web/produits/1/new-price



###


PATCH http://localhost:8085/api/v1/web/produits/1/new-price?newPrix=12.0
Content-Type: application/json

{
    "newPrix": 75.50
}
